export const post_data = [
    {
        id:1,
        taskTitle:"Write Blog Post",
        taskType:"Writing",
        taskDescription:"Create a well-researched blog post of 800-1000 words on the topic provided. Ensure th content is original, engaging and...",
        taskCompensation:25,
        taskTimeline:14,
        taskRespondents:10,
        locationPreference:"Abuja",
        taskRequirement:"Must have a writing degree...",
        taskAdditionalUpload:"",
        taskLinkUpload:"",
        taskLinkUploadTwo:""
    },
    {
        id:2,
        taskTitle:"Video Review",
        taskType:"Review",
        taskDescription:"Watch and review a short product video providing feedback on its clarity and content. Share your thoughts on the product's features...",
        taskCompensation:40,
        taskTimeline:28,
        taskRespondents:14,
        locationPreference:"Lokoja",
        taskRequirement:"Must have a writing degree...",
        taskAdditionalUpload:"",
        taskLinkUpload:"",
        taskLinkUploadTwo:""
    },
    {
        id:3,
        taskTitle:"Graphic Design",
        taskType:"Design",
        taskDescription:"Create a visually appealling graphic design for social media promotion. Use vibrant colors and engaging visuals to attract the target aud...",
        taskCompensation:25,
        taskTimeline:14,
        taskRespondents:10,
        locationPreference:"Abuja",
        taskRequirement:"Must have a writing degree...",
        taskAdditionalUpload:"",
        taskLinkUpload:"",
        taskLinkUploadTwo:""
    },
    {
        id:4,
        taskTitle:"Web Dev Project",
        taskType:"Web Development",
        taskDescription:"Develop a responsive website for a client, following the provided design mockup. Impement interactive feaures and ensure cre...",
        taskCompensation:25,
        taskTimeline:14,
        taskRespondents:10,
        locationPreference:"Abuja",
        taskRequirement:"Must have a writing degree...",
        taskAdditionalUpload:"",
        taskLinkUpload:"",
        taskLinkUploadTwo:""
    },
    {
        id:5,
        taskTitle:"Video Review",
        taskType:"Review",
        taskDescription:"Create a well-researched blog post of 800-1000 words on the topic provided. Ensure th content is original, engaging and...",
        taskCompensation:25,
        taskTimeline:14,
        taskRespondents:10,
        locationPreference:"Abuja",
        taskRequirement:"Must have a writing degree...",
        taskAdditionalUpload:"",
        taskLinkUpload:"",
        taskLinkUploadTwo:""
    },
    {
        id:6,
        taskTitle:"Write Blog Post",
        taskType:"Writing",
        taskDescription:"Create a well-researched blog post of 800-1000 words on the topic provided. Ensure th content is original, engaging and...",
        taskCompensation:25,
        taskTimeline:14,
        taskRespondents:10,
        locationPreference:"Abuja",
        taskRequirement:"Must have a writing degree...",
        taskAdditionalUpload:"",
        taskLinkUpload:"",
        taskLinkUploadTwo:""
    },
    {
        id:7,
        taskTitle:"Write Blog Post",
        taskType:"Writing",
        taskDescription:"Create a well-researched blog post of 800-1000 words on the topic provided. Ensure th content is original, engaging and...",
        taskCompensation:25,
        taskTimeline:14,
        taskRespondents:10,
        locationPreference:"Abuja",
        taskRequirement:"Must have a writing degree...",
        taskAdditionalUpload:"",
        taskLinkUpload:"",
        taskLinkUploadTwo:""
    },
    {
        id:8,
        taskTitle:"Write Blog Post",
        taskType:"Writing",
        taskDescription:"Create a well-researched blog post of 800-1000 words on the topic provided. Ensure th content is original, engaging and...",
        taskCompensation:25,
        taskTimeline:14,
        taskRespondents:10,
        locationPreference:"Abuja",
        taskRequirement:"Must have a writing degree...",
        taskAdditionalUpload:"",
        taskLinkUpload:"",
        taskLinkUploadTwo:""
    },
    {
        id:9,
        taskTitle:"Write Blog Post",
        taskType:"Writing",
        taskDescription:"Create a well-researched blog post of 800-1000 words on the topic provided. Ensure th content is original, engaging and...",
        taskCompensation:25,
        taskTimeline:14,
        taskRespondents:10,
        locationPreference:"Abuja",
        taskRequirement:"Must have a writing degree...",
        taskAdditionalUpload:"",
        taskLinkUpload:"",
        taskLinkUploadTwo:""
    },
    {
        id:10,
        taskTitle:"Write Blog Post",
        taskType:"Writing",
        taskDescription:"Create a well-researched blog post of 800-1000 words on the topic provided. Ensure th content is original, engaging and...",
        taskCompensation:25,
        taskTimeline:14,
        taskRespondents:10,
        locationPreference:"Abuja",
        taskRequirement:"Must have a writing degree...",
        taskAdditionalUpload:"",
        taskLinkUpload:"",
        taskLinkUploadTwo:""
    },
    {
        id:11,
        taskTitle:"Write Blog Post",
        taskType:"Writing",
        taskDescription:"Create a well-researched blog post of 800-1000 words on the topic provided. Ensure th content is original, engaging and...",
        taskCompensation:25,
        taskTimeline:14,
        taskRespondents:10,
        locationPreference:"Abuja",
        taskRequirement:"Must have a writing degree...",
        taskAdditionalUpload:"",
        taskLinkUpload:"",
        taskLinkUploadTwo:""
    },
    {
        id:12,
        taskTitle:"Write Blog Post",
        taskType:"Writing",
        taskDescription:"Create a well-researched blog post of 800-1000 words on the topic provided. Ensure th content is original, engaging and...",
        taskCompensation:25,
        taskTimeline:14,
        taskRespondents:10,
        locationPreference:"Abuja",
        taskRequirement:"Must have a writing degree...",
        taskAdditionalUpload:"",
        taskLinkUpload:"",
        taskLinkUploadTwo:""
    },
    {
        id:13,
        taskTitle:"Write Blog Post",
        taskType:"Writing",
        taskDescription:"Create a well-researched blog post of 800-1000 words on the topic provided. Ensure th content is original, engaging and...",
        taskCompensation:25,
        taskTimeline:14,
        taskRespondents:10,
        locationPreference:"Abuja",
        taskRequirement:"Must have a writing degree...",
        taskAdditionalUpload:"",
        taskLinkUpload:"",
        taskLinkUploadTwo:""
    },
    {
        id:14,
        taskTitle:"Write Blog Post",
        taskType:"Writing",
        taskDescription:"Create a well-researched blog post of 800-1000 words on the topic provided. Ensure th content is original, engaging and...",
        taskCompensation:25,
        taskTimeline:14,
        taskRespondents:10,
        locationPreference:"Abuja",
        taskRequirement:"Must have a writing degree...",
        taskAdditionalUpload:"",
        taskLinkUpload:"",
        taskLinkUploadTwo:""
    },
    {
        id:15,
        taskTitle:"Write Blog Post",
        taskType:"Writing",
        taskDescription:"Create a well-researched blog post of 800-1000 words on the topic provided. Ensure th content is original, engaging and...",
        taskCompensation:25,
        taskTimeline:14,
        taskRespondents:10,
        locationPreference:"Abuja",
        taskRequirement:"Must have a writing degree...",
        taskAdditionalUpload:"",
        taskLinkUpload:"",
        taskLinkUploadTwo:""
    },
    {
        id:16,
        taskTitle:"Write Blog Post",
        taskType:"Writing",
        taskDescription:"Create a well-researched blog post of 800-1000 words on the topic provided. Ensure th content is original, engaging and...",
        taskCompensation:25,
        taskTimeline:14,
        taskRespondents:10,
        locationPreference:"Abuja",
        taskRequirement:"Must have a writing degree...",
        taskAdditionalUpload:"",
        taskLinkUpload:"",
        taskLinkUploadTwo:""
    },
    {
        id:17,
        taskTitle:"Write Blog Post",
        taskType:"Writing",
        taskDescription:"Create a well-researched blog post of 800-1000 words on the topic provided. Ensure th content is original, engaging and...",
        taskCompensation:25,
        taskTimeline:14,
        taskRespondents:10,
        locationPreference:"Abuja",
        taskRequirement:"Must have a writing degree...",
        taskAdditionalUpload:"",
        taskLinkUpload:"",
        taskLinkUploadTwo:""
    },
    {
        id:18,
        taskTitle:"Write Blog Post",
        taskType:"Writing",
        taskDescription:"Create a well-researched blog post of 800-1000 words on the topic provided. Ensure th content is original, engaging and...",
        taskCompensation:25,
        taskTimeline:14,
        taskRespondents:10,
        locationPreference:"Abuja",
        taskRequirement:"Must have a writing degree...",
        taskAdditionalUpload:"",
        taskLinkUpload:"",
        taskLinkUploadTwo:""
    },
]

